#!/usr/bin/env python3
"""
load_backtest_journal.py — Obsidian-native, backtester-ONLY trade journal loader.

Reads the replay backtester's session sidecars (../sessions/session_*.json) and
writes an Obsidian-first journal into the Trading vault:

  <VAULT>/Trading Brain/Mentor/Backtest Journal/
    Sessions/<real_date> NQ <id8> <GRADE>.md   # one note per session (light, human)
    trades.ndjson                              # canonical flat trade store (heavy)
    Backtest Sessions.base                     # native Bases dashboard (no plugin)
    Backtest Dashboard.md                      # static-computed + Dataview dashboard

Design (two-layer, idempotent — same principle as the prior SQLite version):
  * OBJECTIVE data (stats, per-trade fields) is regenerated from the source JSON
    on every run.
  * ANNOTATIONS are PRESERVED across reloads:
      - session notes: frontmatter annotation keys (regime/grade/psych_*/lesson)
        and the entire human body BELOW the AUTO block are never clobbered.
      - trades.ndjson: annotation keys (setup_tag/levels_in_play/psych_state/
        went_right/went_wrong/note) are carried forward per (session_id,order_id).
  * stdlib only (no pyyaml/duckdb). Frontmatter is kept FLAT (one line per key)
    so it round-trips with a tiny parser; long-form psych goes in body sections.
  * entry_et from the replay tool is ALREADY correct ET (verified vs entry_ns) —
    NOT the broker-export -1h. real_date is decoded from entry_ns.
  * These are REPLAY/backtest trades — kept out of the live Mentor/Trade Log.

Usage:
  python3 load_backtest_journal.py --all --min-trades 9   # backfill real sessions
  python3 load_backtest_journal.py 20260609_133346_77a655 # one id
  python3 load_backtest_journal.py --all --seed           # apply annotations.json on first-create
  python3 load_backtest_journal.py --install-dashboard     # (re)write .base + dashboard only
Env override: BACKTEST_JOURNAL_VAULT=/path/to/Backtest Journal
"""
import argparse, glob, json, os, re
from datetime import datetime
from zoneinfo import ZoneInfo

HERE = os.path.dirname(os.path.abspath(__file__))
SESSIONS_DIR = os.path.normpath(os.path.join(HERE, "..", "sessions"))
ANNOTATIONS = os.path.join(HERE, "annotations.json")
ET = ZoneInfo("America/New_York")

DEFAULT_VAULT = os.path.expanduser(
    "~/Library/Mobile Documents/iCloud~md~obsidian/Documents/Trading/"
    "Trading Brain/Mentor/Backtest Journal")
VAULT = os.environ.get("BACKTEST_JOURNAL_VAULT", DEFAULT_VAULT)

AUTO_START = "<!-- AUTO:STATS:START — regenerated by load_backtest_journal.py; do not edit between markers -->"
AUTO_END = "<!-- AUTO:STATS:END -->"

# frontmatter: objective keys (refreshed) vs annotation keys (preserved)
FM_OBJ = ["session_id","real_date","weekday","mode","n_trades","win_pct","net_usd",
    "net_ticks","expectancy","profit_factor","avg_win","avg_loss","max_dd",
    "direction_skill","selection_skill","open5m_range","first_entry_et","last_exit_et",
    "in_window_trades","fade_trades","aligned_trades","fade_net_ticks","aligned_net_ticks",
    "source_file","loaded_at","reviewed"]
FM_ANN = ["regime","grade","psych_pre","psych_during","psych_post","lesson"]
TRADE_ANN = ["setup_tag","levels_in_play","psych_state","went_right","went_wrong","note"]


# ----------------------------------------------------------------- derivations
def fade_or_aligned(side, fd):
    if fd is None: return "unknown"
    if side == "LONG":  return "fade" if fd < 0 else "aligned"
    return "fade" if fd > 0 else "aligned"           # SHORT

def time_window(dt):
    m = dt.hour * 60 + dt.minute
    if 570 <= m < 600: return "open"
    if 600 <= m < 660: return "10-11"
    if 660 <= m < 780: return "lunch"
    if 780 <= m < 900: return "13-15"
    return "other"

def provisional_regime(stats):
    ds = stats.get("direction_skill") or 0
    if ds >= 20:  return "range-chop"
    if ds <= -20: return "trend"
    return "mixed"


# --------------------------------------------------------------- flat YAML I/O
def yaml_scalar(v):
    if v is None: return '""'
    if isinstance(v, bool): return "true" if v else "false"
    if isinstance(v, (int, float)): return repr(v)
    s = str(v)
    if s == "": return '""'
    if re.search(r'[:#\[\]{}\n"]', s) or s != s.strip():
        return json.dumps(s, ensure_ascii=False)
    return s

def parse_frontmatter(text):
    """Return (fm: {key: raw_str}, body: str). Flat one-line-per-key only."""
    if not text.startswith("---"):
        return {}, text
    end = text.find("\n---", 3)
    if end == -1:
        return {}, text
    block = text[3:end].strip("\n")
    body = text[end + 4:]
    if body.startswith("\n"): body = body[1:]
    fm = {}
    for line in block.splitlines():
        m = re.match(r'^([A-Za-z0-9_]+):\s?(.*)$', line)
        if m: fm[m.group(1)] = m.group(2)
    return fm, body

def fm_value(raw):
    """Decode a stored frontmatter raw string to a python str for reuse."""
    raw = raw.strip()
    if raw and raw[0] in '"[':
        try: return json.loads(raw)
        except Exception: pass
    return raw


# ------------------------------------------------------------------ load logic
def build_session(path):
    d = json.load(open(path))
    sid = d.get("session_id") or os.path.basename(path)[8:-5]
    trades = d.get("trades") or []
    if not trades: return None
    s = d.get("stats", {})
    t0 = datetime.fromtimestamp(trades[0]["entry_ns"] / 1e9, ET)
    tN = datetime.fromtimestamp(trades[-1]["exit_ns"] / 1e9, ET)
    fade = aligned = inwin = 0
    fade_tk = al_tk = 0
    trows = []
    for t in trades:
        edt = datetime.fromtimestamp(t["entry_ns"] / 1e9, ET)
        fa = fade_or_aligned(t["side"], t.get("flow_delta_entry"))
        win = time_window(edt)
        tk = t.get("pnl_ticks") or 0
        if fa == "fade": fade += 1; fade_tk += tk
        elif fa == "aligned": aligned += 1; al_tk += tk
        if win in ("10-11", "13-15"): inwin += 1
        trows.append({
            "session_id": sid, "order_id": t.get("order_id"),
            "real_date": edt.date().isoformat(), "side": t["side"], "size": t.get("size"),
            "instrument": t.get("instrument"), "entry_et": t.get("entry_et"), "exit_et": t.get("exit_et"),
            "entry_ns": t.get("entry_ns"), "exit_ns": t.get("exit_ns"),
            "entry_px_disp": t.get("entry_px_disp"), "exit_px_disp": t.get("exit_px_disp"),
            "exit_reason": t.get("exit_reason"), "pnl_ticks": tk, "pnl_net": t.get("pnl_net"),
            "mfe_ticks": t.get("mfe_ticks"), "mae_ticks": t.get("mae_ticks"), "hold_s": t.get("hold_s"),
            "stop_tk": t.get("stop_tk"), "target_tk": t.get("target_tk"), "trail_tk": t.get("trail_tk"),
            "arm_tk": t.get("arm_tk"), "flow_delta_entry": t.get("flow_delta_entry"),
            "fade_or_aligned": fa, "time_window": win,
            "coinflip_ev_net": t.get("coinflip_ev_net"), "random_time_ev_net": t.get("random_time_ev_net"),
        })
    net_tk = sum(t["pnl_ticks"] for t in trows)
    sess = {
        "session_id": sid, "real_date": t0.date().isoformat(), "weekday": t0.strftime("%a"),
        "mode": d.get("mode"), "n_trades": s.get("n", len(trows)), "win_pct": s.get("wr"),
        "net_usd": s.get("net"), "net_ticks": net_tk, "expectancy": s.get("expectancy"),
        "profit_factor": s.get("pf"), "avg_win": s.get("avg_win"), "avg_loss": s.get("avg_loss"),
        "max_dd": s.get("max_dd"), "direction_skill": s.get("direction_skill"),
        "selection_skill": s.get("selection_skill"), "open5m_range": s.get("open5m_range"),
        "first_entry_et": t0.strftime("%H:%M:%S"), "last_exit_et": tN.strftime("%H:%M:%S"),
        "in_window_trades": inwin, "fade_trades": fade, "aligned_trades": aligned,
        "fade_net_ticks": fade_tk, "aligned_net_ticks": al_tk,
        "source_file": os.path.basename(path), "loaded_at": datetime.now(ET).isoformat(timespec="seconds"),
    }
    return sess, trows


def note_path(sess, existing_index):
    """Stable filename: '<date> NQ <id8> <GRADE>.md'. Reuse existing if grade changed."""
    sid = sess["session_id"]
    if sid in existing_index:
        return existing_index[sid]
    id8 = sid.split("_")[-1]
    return os.path.join(VAULT, "Sessions", f"{sess['real_date']} NQ {id8}.md")


def index_existing_notes():
    idx = {}
    for p in glob.glob(os.path.join(VAULT, "Sessions", "*.md")):
        try:
            fm, _ = parse_frontmatter(open(p).read())
        except Exception:
            continue
        sid = fm.get("session_id")
        if sid: idx[sid.strip().strip('"')] = p
    return idx


def auto_block(sess, trows):
    L = []
    L.append(AUTO_START)
    g = sess.get("_grade") or "—"
    L.append(f"> **{sess['real_date']} {sess['weekday']}** · {sess['n_trades']} trades · "
             f"WR {sess['win_pct']}% · net **${sess['net_usd']}** ({sess['net_ticks']:+} tk) · "
             f"PF {sess['profit_factor']} · dir-skill {sess['direction_skill']} · "
             f"regime *{sess.get('_regime','?')}* · grade **{g}**")
    L.append("")
    L.append(f"- **Fade vs aligned:** {sess['fade_trades']} fade ({sess['fade_net_ticks']:+}tk) · "
             f"{sess['aligned_trades']} aligned ({sess['aligned_net_ticks']:+}tk)")
    L.append(f"- **In-window (10-11/13-15):** {sess['in_window_trades']}/{sess['n_trades']} · "
             f"first entry {sess['first_entry_et']} ET · max DD ${sess['max_dd']}")
    exits = {}
    for t in trows: exits[t["exit_reason"]] = exits.get(t["exit_reason"], 0) + 1
    L.append(f"- **Exits:** " + " · ".join(f"{k} {v}" for k, v in sorted(exits.items())))
    L.append("")
    L.append("| # | ET | side | sz | exit | ticks | $ | f/a | win |")
    L.append("|--:|----|------|---:|------|------:|--:|-----|-----|")
    for t in trows:
        L.append(f"| {t['order_id']} | {t['entry_et']} | {t['side']} | {t['size']} | "
                 f"{t['exit_reason']} | {t['pnl_ticks']:+} | {t['pnl_net']} | "
                 f"{t['fade_or_aligned'][:4]} | {t['time_window']} |")
    L.append("")
    L.append(f"*Canonical per-trade data (with annotations) → `trades.ndjson`, "
             f"`session_id == {sess['session_id']}`. Regenerated; edit below the marker, not inside.*")
    L.append(AUTO_END)
    return "\n".join(L)


def human_scaffold(ann):
    def blk(label, key):
        v = (ann or {}).get(key, "")
        return f"## {label}\n\n{v}\n"
    return "\n".join([
        blk("What went right", "what_went_right"),
        blk("What went wrong", "what_went_wrong"),
        blk("Lesson", "lesson"),
        "## Setups & levels in play\n\n\n",
        "## Free notes\n\n" + (ann or {}).get("note", "") + "\n",
        "---\n[[Backtest Dashboard]] · [[Trading Desk]]\n",
    ])


def write_session_note(sess, trows, seed_ann, do_seed):
    os.makedirs(os.path.join(VAULT, "Sessions"), exist_ok=True)
    idx = index_existing_notes()
    path = note_path(sess, idx)
    exists = os.path.exists(path)
    prev_fm, prev_body = ({}, "")
    if exists:
        prev_fm, full_body = parse_frontmatter(open(path).read())
        # human body = everything after AUTO_END
        if AUTO_END in full_body:
            prev_body = full_body.split(AUTO_END, 1)[1].lstrip("\n")
        else:
            prev_body = full_body

    # resolve annotations: preserve existing > seed (first create) > default
    ann = {}
    for k in FM_ANN:
        if exists and prev_fm.get(k) not in (None, "", '""'):
            ann[k] = fm_value(prev_fm[k])
        elif do_seed and seed_ann:
            ann[k] = seed_ann.get(k, "")
        else:
            ann[k] = ""
    reviewed = bool(seed_ann) or (exists and str(prev_fm.get("reviewed", "")).strip() == "true")
    if not ann.get("regime"):
        ann["regime"] = provisional_regime(sess)
    sess["_grade"] = ann.get("grade") or ""
    sess["_regime"] = ann.get("regime")

    # frontmatter
    fm = {"tags": "[backtest-session, nq, replay]"}
    for k in FM_OBJ:
        if k == "reviewed":
            fm[k] = "true" if reviewed else "false"
        else:
            fm[k] = yaml_scalar(sess[k])
    for k in FM_ANN:
        fm[k] = yaml_scalar(ann.get(k, ""))

    lines = ["---"]
    lines.append(f"tags: {fm['tags']}")
    for k in FM_OBJ + FM_ANN:
        lines.append(f"{k}: {fm[k]}")
    lines.append("---")
    fm_text = "\n".join(lines)

    body = (prev_body if exists else human_scaffold(seed_ann))
    content = fm_text + "\n\n" + auto_block(sess, trows) + "\n\n" + body
    open(path, "w").write(content)
    return path, ("updated" if exists else "created")


def merge_ndjson(all_trows):
    """Write trades.ndjson, preserving annotation keys per (session_id, order_id)."""
    path = os.path.join(VAULT, "trades.ndjson")
    prev = {}
    if os.path.exists(path):
        for line in open(path):
            line = line.strip()
            if not line: continue
            try: r = json.loads(line)
            except Exception: continue
            prev[(r.get("session_id"), r.get("order_id"))] = r
    out = []
    for r in all_trows:
        key = (r["session_id"], r["order_id"])
        old = prev.get(key, {})
        for k in TRADE_ANN:
            if old.get(k) not in (None, ""):
                r[k] = old[k]
            else:
                r.setdefault(k, "")
        out.append(r)
    # keep any previously-loaded sessions not in this run untouched
    seen = {(r["session_id"], r["order_id"]) for r in all_trows}
    for key, r in prev.items():
        if key not in seen:
            out.append(r)
    out.sort(key=lambda r: (r["real_date"], r["session_id"], r["order_id"]))
    with open(path, "w") as f:
        for r in out:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")
    return path, len(out)


# ---------------------------------------------------------------- dashboards
def install_dashboard(force=True):
    os.makedirs(VAULT, exist_ok=True)
    base_path = os.path.join(VAULT, "Backtest Sessions.base")
    if force or not os.path.exists(base_path):
        open(base_path, "w").write(BASE_FILE)
    dash_path = os.path.join(VAULT, "Backtest Dashboard.md")
    if force or not os.path.exists(dash_path):
        open(dash_path, "w").write(DASHBOARD_MD)
    return base_path, dash_path


def refresh_dashboard_stats():
    """Compute static aggregates from trades.ndjson + session notes and inject
    them into Backtest Dashboard.md between AUTO markers (works with zero plugins)."""
    nd = os.path.join(VAULT, "trades.ndjson")
    if not os.path.exists(nd): return
    trades = [json.loads(l) for l in open(nd) if l.strip()]
    # regime per session from notes
    regime = {}; grade = {}; reviewed = {}
    sess_net = {}
    for p in glob.glob(os.path.join(VAULT, "Sessions", "*.md")):
        fm, _ = parse_frontmatter(open(p).read())
        sid = (fm.get("session_id") or "").strip().strip('"')
        if not sid: continue
        regime[sid] = fm_value(fm.get("regime", "") or "?")
        grade[sid] = fm_value(fm.get("grade", "") or "")
        reviewed[sid] = str(fm.get("reviewed", "")).strip() == "true"
        try: sess_net[(fm_value(fm.get("real_date")), sid)] = float(fm.get("net_usd"))
        except Exception: pass

    # fade vs aligned by regime
    agg = {}
    for t in trades:
        reg = regime.get(t["session_id"], "?")
        fa = t["fade_or_aligned"]
        k = (reg, fa)
        a = agg.setdefault(k, [0, 0, 0])     # n, wins, net_ticks
        a[0] += 1; a[1] += 1 if t["pnl_ticks"] > 0 else 0; a[2] += t["pnl_ticks"]
    rows = ["| regime | f/a | n | win% | net ticks |", "|---|---|--:|--:|--:|"]
    for (reg, fa) in sorted(agg):
        n, w, tk = agg[(reg, fa)]
        rows.append(f"| {reg} | {fa} | {n} | {round(100*w/n,1)} | {tk:+} |")

    # grade distribution
    gd = {}
    for sid, g in grade.items():
        g = g or "(unreviewed)"
        gd[g] = gd.get(g, 0) + 1
    grows = ["| grade | sessions |", "|---|--:|"] + \
            [f"| {g} | {gd[g]} |" for g in sorted(gd)]

    # equity curve (session-ordered cumulative net $)
    eq = []; cum = 0.0
    for (dt, sid) in sorted(sess_net):
        cum += sess_net[(dt, sid)]
        eq.append((dt, sid.split("_")[-1], sess_net[(dt, sid)], round(cum, 1)))
    erows = ["| # | date | id | net $ | cum $ |", "|--:|---|---|--:|--:|"]
    for i, (dt, idd, net, c) in enumerate(eq, 1):
        erows.append(f"| {i} | {dt} | {idd} | {net:+} | {c:+} |")

    n_sess = len({t["session_id"] for t in trades})
    wr_all = round(100 * sum(1 for t in trades if t["pnl_ticks"] > 0) / len(trades), 1)
    block = "\n".join([
        AUTO_START,
        f"*Static snapshot — {n_sess} sessions · {len(trades)} trades · "
        f"overall WR {wr_all}% · last refresh {datetime.now(ET).strftime('%Y-%m-%d %H:%M ET')}. "
        f"Re-run the loader to refresh. Live versions below need the Dataview plugin.*",
        "", "### Fade vs aligned — by regime", *rows,
        "", "### Grade distribution", *grows,
        "", "### Equity curve (session-ordered cumulative net $)", *erows,
        AUTO_END,
    ])
    dash = os.path.join(VAULT, "Backtest Dashboard.md")
    text = open(dash).read() if os.path.exists(dash) else DASHBOARD_MD
    if AUTO_START in text and AUTO_END in text:
        text = re.sub(re.escape(AUTO_START) + r".*?" + re.escape(AUTO_END), block, text, flags=re.S)
    else:
        text = text.replace("<!-- STATIC-SNAPSHOT -->", block)
    open(dash, "w").write(text)


# ---------------------------------------------------------------------- main
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("ids", nargs="*")
    ap.add_argument("--all", action="store_true")
    ap.add_argument("--seed", action="store_true", help="seed annotations.json on first-create")
    ap.add_argument("--min-trades", type=int, default=1)
    ap.add_argument("--install-dashboard", action="store_true")
    args = ap.parse_args()

    seed = {}
    if os.path.exists(ANNOTATIONS):
        seed = json.load(open(ANNOTATIONS)).get("sessions", {})

    install_dashboard(force=True)
    if args.install_dashboard and not (args.all or args.ids):
        refresh_dashboard_stats()
        print(f"installed dashboard + base into {VAULT}")
        return

    if args.all:
        paths = sorted(glob.glob(os.path.join(SESSIONS_DIR, "session_*.json")))
    else:
        paths = []
        for sid in args.ids:
            p = os.path.join(SESSIONS_DIR, f"session_{sid}.json")
            if not os.path.exists(p):
                hits = glob.glob(os.path.join(SESSIONS_DIR, f"*{sid}*.json"))
                p = hits[0] if hits else p
            paths.append(p)

    all_trows = []; n_sess = 0
    for p in paths:
        if not os.path.exists(p):
            print(f"  MISSING {p}"); continue
        built = build_session(p)
        if not built: continue
        sess, trows = built
        if len(trows) < args.min_trades: continue
        sann = seed.get(sess["session_id"])
        do_seed = args.seed and sann is not None
        path, status = write_session_note(sess, trows, sann, do_seed)
        all_trows.extend(trows); n_sess += 1
        print(f"  {status:7} {os.path.basename(path)}  ({len(trows)} trades)")

    nd_path, total = merge_ndjson(all_trows)
    refresh_dashboard_stats()
    print(f"== {n_sess} sessions written · trades.ndjson now {total} rows")
    print(f"   vault: {VAULT}")


# ------------------------------------------------------------- vault templates
BASE_FILE = """\
# Bases dashboard for the backtester journal (core plugin — no install needed).
filters:
  and:
    - file.hasTag("backtest-session")
views:
  - type: table
    name: All Sessions
    order:
      - real_date
      - weekday
      - n_trades
      - win_pct
      - net_usd
      - profit_factor
      - direction_skill
      - in_window_trades
      - regime
      - grade
      - reviewed
  - type: table
    name: Losing Sessions
    filters:
      and:
        - net_usd < 0
    order:
      - real_date
      - n_trades
      - net_usd
      - profit_factor
      - direction_skill
      - regime
      - grade
  - type: table
    name: By Regime
    order:
      - regime
      - real_date
      - n_trades
      - net_usd
      - fade_net_ticks
      - aligned_net_ticks
      - grade
  - type: table
    name: Fade vs Aligned
    order:
      - real_date
      - regime
      - fade_trades
      - fade_net_ticks
      - aligned_trades
      - aligned_net_ticks
      - grade
  - type: table
    name: Needs Review
    filters:
      and:
        - reviewed == false
    order:
      - real_date
      - n_trades
      - net_usd
      - regime
"""

DASHBOARD_MD = """\
---
tags: [backtest, dashboard, nq]
---

# 📈 Backtest Journal — Dashboard

Backtester-ONLY review of the NQ replay sessions. Heavy per-trade data lives in
`trades.ndjson`; each session has a light note in `Sessions/`. Native table views
below via **Bases** (core, no install). The **static snapshot** updates every time
the loader runs — browsable with zero plugins.

## 🗂️ Sessions (Bases — native)

![[Backtest Sessions.base]]

## 📊 Aggregates (static snapshot)

<!-- STATIC-SNAPSHOT -->

---

## 🔌 Live aggregates (needs the Dataview community plugin)

> Install **Dataview** to render these live. Until then, the static snapshot above
> (refreshed by the loader) and the Bases views cover the same ground.

### Scoreboard
```dataview
TABLE real_date AS date, n_trades AS n, win_pct AS "WR%", net_usd AS "net $",
      profit_factor AS PF, direction_skill AS "dir-skill", regime, grade
FROM #backtest-session
SORT real_date ASC
```

### Net $ by regime
```dataview
TABLE length(rows) AS sessions, sum(rows.net_usd) AS "net $",
      sum(rows.fade_net_ticks) AS "fade tk", sum(rows.aligned_net_ticks) AS "aligned tk"
FROM #backtest-session
GROUP BY regime
```

### Grade distribution
```dataview
TABLE length(rows) AS sessions FROM #backtest-session
GROUP BY grade
```

### Equity curve (per-trade, dataviewjs)
```dataviewjs
// reads trades.ndjson via the Obsidian vault adapter and plots cumulative $
const raw = await app.vault.adapter.read(
  dv.current().file.folder + "/trades.ndjson").catch(() => "");
const rows = raw.trim().split("\\n").filter(Boolean).map(JSON.parse);
rows.sort((a,b)=> (a.real_date+a.session_id+String(a.order_id)).localeCompare(
                  b.real_date+b.session_id+String(b.order_id)));
let cum=0; const pts=rows.map(r=>{cum+=r.pnl_net; return cum.toFixed(0);});
dv.paragraph("Cumulative $ over " + rows.length + " trades: ends at $" + cum.toFixed(0));
dv.paragraph(pts.join(" · "));
```

---
[[Trading Desk]] · [[11 - Validation Tracker]]
"""


if __name__ == "__main__":
    main()
